In [5]:
m1 = np.zeros((3,5),int)

#convert all zeros in matrix to 3
m1 = m1 + 3

#print matrix
print(m1)


#create an array from 0 to 14, specify integers, then reshape to a 3x5 matrix
m2 = np.arange(0,15,dtype=int).reshape((3,5))

#print matrix
print(m2)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
